/**
* @class PaSequentialDataBloc
* A simple data manipulation class.
*
* A PaSequentialDataBloc is used to store data in BigEndian Format
* that can be acceded sequentially
* 
* @author J.C. Hoelt <jeko@free.fr>
* @version 29/04/2001
*
* file : PaSequentialDataBloc.h
*
* use : to create a data structure :
* 	- you must first create a "root" DataBloc
*		using the static method CreateBaseBloc () with no parameters.
* 	- then you can add data to the bloc.
* 	- you can also create subBlocs with CreateSubBloc (), which take the
*		name of the SubBloc in parameter.
* 	- when the Data structure is complete, a call to the method Finalize ()
*		with the root DataBloc will complete the work, by setting all the
*		label with the correct value into the final struct, and return a
*		table of guint8 (bytes)... all data are now stored in Big Endian.
*
*	loading...
*
*	This table can be loaded with CreateBaseBloc (table), which will recreate
*		the structure in read-only access mode
*/

#ifndef _PaSequentialDataBloc_H
#define _PaSequentialDataBloc_H

// deja dans paarray #include "patypes.h"
#include "paarray.h"
#include "pacharbuffer.h"
#include "paexception.h"

namespace patools {

class PaSequentialDataBloc
{
	public:
	
		enum ExceptionId
		{
			NO_SUCH_FILE=0,
			EXISTING_SUBBLOC,
			COULD_NOT_CREATE_FILE,
			NO_SUCH_BLOC,
			NOT_A_ROOT_BLOC,
            OUT_OF_BOUNDS,
			END_OF_BLOC
		} ;

		/**
		* @name Creation Methods
		* @{
		*/

		/**
		* build a PaDataBloc.
		* @return a PaDataBloc that can be used as the root of a data structure
		*/
		static PaSequentialDataBloc * CreateBaseBloc () ;

		/**
		* recreate a PaSequentialDataBloc data structure
		* @param data a PaArray of bytes, generated by Finalize.
		* @return the root databloc
		* @see Finalize ()
		*/
    static PaSequentialDataBloc * CreateBaseBloc (const PaArray <guint8> & data) ;

		/**
		* recreate a PaSequentialDataBloc data structure
		*
		* @param fileName a file of generated by Finalize or FinalizeAndWriteToDisk
		*
		* @return the root databloc
		* @exception PaException "NO SUCH FILE". (id = NO_SUCH_FILE)
		*
		* @see Finalize()
		* @see FinalizeAndWriteToDisk ()
		* @see CreateBaseBloc (const PaArray <guint8> &)
		*/
		static PaSequentialDataBloc * LoadBaseBloc (const char * fileName)
			throw (PaException) ;


		/**
		* Create a PaSequentialDataBloc referenced into this bloc
		*
		* You can use slashed notation, (NOT YET)
		*
		* Exemple :
		* 	A call to root->CreateSubBloc ("INFO/NAME") will create a SubBloc called INFO
		* 	into the root bloc if it didn't exists, and then a SubBloc called NAME into
		* 	the INFO subbloc..
		*
		* @param label The name of the subbloc
		* @return A pointer to the created SubBloc
		* @exception PaException "EXISTING SUBBLOC" (id = EXISTING_SUBBLOC)
		*/
		PaSequentialDataBloc * CreateSubBloc (const CharBuffer & label)
			throw (PaException) ;
			
		/** @} end of creation methods */


		/**
		* @name Sequential Write Methods
		* add data into the bloc
		* @{
		*/

		void Write (const char * cb) ;
		void Write (const CharBuffer & cb) ;
		void Write (const guint32 i) ;
		void Write (const gint32 i) ;
		void Write (const guint16 i) ;
		void Write (const gint16 i) ;
		void Write (const guint8 i) ;
		void Write (const gint8 i) ;
		void Write (const gfloat f) ;
		// void Write (const gdouble f) ;

		/** @} */

		/**
		* finalize a data structure.
		* @return a buffer of bytes that CreateBaseBloc can use later to rebuild a PSDB.
		* @see CreateBaseBloc ()
		*/
		PaArray <guint8> Finalize () ;
		
		/**
		* same thing than Finalize.
		* but the data are saved into a file.
		* @exception PaException "COULD NOT CREATE FILE" (id = COULD_NOT_CREATE_FILE)
		* @see Finalize ()
		* @see LoadBaseBloc ()
		*/
		void FinalizeAndWriteToDisk (const char * fileName) throw (PaException) ;


		/**
		* @name Sequential Read Methods
		* Data access methods, read sequentially a data into the bloc
		* @{
		*/

		CharBuffer ReadCharBuffer () const ;
		guint32 ReadUInt32 () const ;
		gint32 ReadInt32 () const ;
		guint16 ReadUInt16 () const ;
		gint16 ReadInt16 () const ;
		guint8 ReadUInt8 () const ;
		gint8 ReadInt8 () const ;
		gfloat ReadFloat () const ;
		// gdouble ReadDouble () const ;
		
		/** @} */
		
		/** Goto position i */
		void Seek (const guint32 i) const ;

		/**
		* @name Random Read Methods
		* Data access methods, read a data into the bloc from position i
		* @{
		*/

		CharBuffer ReadCharBuffer (const guint32 i) const ;
		guint32 ReadUInt32 (const guint32 i) const ;
		gint32 ReadInt32 (const guint32 i) const ;
		guint16 ReadUInt16 (const guint32 i) const ;
		gint16 ReadInt16 (const guint32 i) const ;
		guint8 ReadUInt8 (const guint32 i) const ;
		gint8 ReadInt8 (const guint32 i) const ;
		gfloat ReadFloat (const guint32 i) const ;
		// gdouble ReadDouble (const guint32 i) const ;

		/** @} */

		/** Size calculation method.
		* @return the number of bytes used by the bloc himself
		* (incuding the labels)
		*/
		guint32 SelfSize () const ;

		/** Size calculation method.
		* @return the number of bytes used by the bloc himself
		*  and all his SubBlocs
		*/
		guint32 TotalSize () const ;


		/** Identification method.
		* @return the name of the PaDataBloc
		*/
		const CharBuffer & Label () const ;

		/** Identification method.
		* @return The complete name of the PaDataBloc
		* example : "ROOT/GRAND-FATHER/(...)/FATHER.NAME"
		*/
		const CharBuffer & LongLabel () const ;


		/** Access method.
		* @return The subbloc with the given name.
		* @exception PaException "NO_SUCH_BLOC" (id = NO_SUCH_BLOCK)
		*/
		PaSequentialDataBloc * SubBloc (const CharBuffer & name)
			throw (PaException) ;

        /** Access method.
         * @return The subbloc with the given name.
         * @exception PaException "NO_SUCH_BLOC" (id = NO_SUCH_BLOCK)
         */
        bool HasSubBloc (const CharBuffer & name) ;
        
		/**
		* The destructor
		* Set the pointer to NULL after destruction
		* @exception PaException "NOT A ROOT BLOC" (id = NOT_A_ROOT_BLOC)
		*/
		static void Free (PaSequentialDataBloc * & psb) throw (PaException) ;


	private:

		/** seul un PaDataBloc existant peut en creer un autre */
		PaSequentialDataBloc (const CharBuffer & longname) ;

		/** interdiction de reproduire un PaDataBloc */
		PaSequentialDataBloc (const PaSequentialDataBloc &) {} ;
		/** interdiction de reproduire un PaDataBloc */
		PaSequentialDataBloc & operator = (const PaSequentialDataBloc &) {return *this;} ;
		
		/** destructor */
		~PaSequentialDataBloc () ;

		/**
		* Données membres
		*/
		
		/** nom du Bloc */
		CharBuffer label ;
		
		/** nom complet */
		CharBuffer longLabel ;
		
		/** bloc de donnés en octets */
		PaArray <guint8> datas ;
		
		/** position de la lecture */
		mutable guint32 readPos ;

		/** tableau des sous-blocs */
		PaArray <PaSequentialDataBloc *> subBlocs ;
		
		/**
		* ce qui suit est utilisé pour Load
		*/
		
		/**
		* Charge le bloc qui commence à l'adresse 'pos' dans le PaArray
		* (nb : fonction recursive, cree aussi tout les sous-blocs)
		*/
		void LoadBloc (PaSequentialDataBloc * bloc, const guint32 pos) ;


		/**
		* ce qui suit est utilisé pour Finalize
		*/

		/**
		* ecrit un bloc à l'interieur d'un autre
		*/
		void WriteBloc (const PaSequentialDataBloc & psb) ;
		
		/** taille du bloc, label, sous-blocs blocs, & table des sous-blocs compris.
		* en fait : tout compris */
		guint32 FinalTotalBlocSize () const;
		
		
		/** Exception launcher */
		class PSDBException : public PaExceptionDesc
		{
			public:
				PSDBException (ExceptionId e) ;
				virtual const char * GetMsg () const ;
				virtual int GetId () const ;
				virtual const char * GetMiscInfo () const ;
			private:
				int id ;
		} ;
} ;
}

#endif
